# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNa2njZtR89z0fzXQBOnq_iLgmQxejES

HMM
"""

!pip install hmmlearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm

states = ["Sunny", "Rainy"]

transition_matrix = np.array([
    [0.8, 0.2],
    [0.4, 0.6]
])

print("\nTransition Matrix:")
print(transition_matrix)

def simulate_markov_chain(start_state, n_steps=20):
    current_state = states.index(start_state)
    sequence = [start_state]
    for _ in range(n_steps):
        current_state = np.random.choice([0, 1], p=transition_matrix[current_state])
        sequence.append(states[current_state])
    return sequence

mc_sequence = simulate_markov_chain("Sunny", 15)
print("\nGenerated Markov Chain Sequence:")
print(mc_sequence)

hidden_states = ["Hot", "Cold"]
observations = ["IceCream", "Coffee"]

model = hmm.MultinomialHMM(n_components=2, n_iter=50)
model.transmat_ = np.array([
    [0.7, 0.3],
    [0.4, 0.6]
])
model.emissionprob_ = np.array([
    [0.8, 0.2],
    [0.3, 0.7]
])
model.startprob_ = np.array([0.6, 0.4])

print("\nTransition Matrix (Hidden States):")
print(model.transmat_)
print("\nEmission Matrix:")
print(model.emissionprob_)

model.n_trials = 1
obs_seq, hidden_seq = model.sample(15)

obs_seq = obs_seq.flatten()
hidden_seq = hidden_seq.flatten()

decoded_obs = [observations[i] for i in obs_seq]
decoded_hidden = [hidden_states[i] for i in hidden_seq]

print("\nGenerated Observations from HMM:")
print(decoded_obs)
print("\nActual Hidden States from HMM:")
print(decoded_hidden)

n_observations = len(observations)
X_decoded = np.zeros((len(obs_seq), n_observations))
X_decoded[np.arange(len(obs_seq)), obs_seq] = 1

logprob, predicted_states = model.decode(X_decoded, algorithm="viterbi")
decoded_predicted = [hidden_states[i] for i in predicted_states]

print("\nPredicted Hidden States (Viterbi):")
print(decoded_predicted)

plt.figure(figsize=(6,4))
sns.heatmap(model.transmat_, annot=True, cmap="Oranges",
            xticklabels=hidden_states, yticklabels=hidden_states)
plt.title("HMM Transition Matrix (Hidden States)")
plt.show()

"""CRF"""

# Install (run once)
# !pip install sklearn-crfsuite

import sklearn_crfsuite

# -----------------------------
# 1. Sample Training Data
# -----------------------------
sentences = [
    [("I", "PRON"), ("love", "VERB"), ("NLP", "NOUN")],
    [("NLP", "NOUN"), ("is", "VERB"), ("fun", "ADJ")]
]

# -----------------------------
# 2. Feature Function
# -----------------------------
def word2features(sent, i):
    word = sent[i][0]
    return {
        'word': word,
        'lower': word.lower(),
        'is_upper': word.isupper(),
        'is_digit': word.isdigit()
    }

def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    return [label for word, label in sent]

# -----------------------------
# 3. Prepare Data
# -----------------------------
X = [sent2features(s) for s in sentences]
y = [sent2labels(s) for s in sentences]

# -----------------------------
# 4. Train Model
# -----------------------------
model = sklearn_crfsuite.CRF()
model.fit(X, y)

# -----------------------------
# 5. User Input Sentence
# -----------------------------
user_input = input("Enter a sentence: ")
test = user_input.split()

# Convert to features
test_features = [
    word2features([(w, "") for w in test], i)
    for i in range(len(test))
]

# -----------------------------
# 6. Prediction
# -----------------------------
pred = model.predict([test_features])

print("\nSentence:", test)
print("Predicted Labels:", pred[0])

"""Relation Extraction"""

import spacy
from spacy.tokens import Doc
from spacy.matcher import Matcher
from spacy import displacy
nlp = spacy.load("en_core_web_sm")
def information_extraction(doc):
    matcher = Matcher(nlp.vocab)

    svo_pattern = [
        {"DEP": "nsubj"},
        {"DEP": "aux", "OP": "?"},
        {"POS": "VERB"},
        {"DEP": "det", "OP": "?"},
        {"DEP": {"IN": ["dobj", "attr", "pobj"]}}
    ]

    matcher.add("SVO_PATTERN", [svo_pattern])
    matches = matcher(doc)

    relations = []
    for _, start, end in matches:
        span = doc[start:end]
        subj = span[0].text
        verb = span[2].lemma_
        obj = span[-1].text
        relations.append((subj, verb, obj))

    return relations
Doc.set_extension("relations", getter=information_extraction, force=True)
text = "Apple is acquiring a U.K. startup. Sundar Pichai is the CEO of Google."
doc = nlp(text)

print("Named Entities:")
for ent in doc.ents:
    print(f"{ent.text} --> {ent.label_}")

displacy.render(doc, style="dep", jupyter=True)
displacy.render(doc, style="ent", jupyter=True)

"""Temporal Extraction"""

import spacy
!pip install py_heideltime
from py_heideltime import heideltime
from datetime import datetime

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

def temporal_extraction(text):

    doc = nlp(text)

    # -------- Extract Time Expressions (spaCy NER) --------
    time_entities = []
    for ent in doc.ents:
        if ent.label_ in ["DATE", "TIME"]:
            time_entities.append((ent.text, ent.label_))

    # -------- Extract Events (Verbs) --------
    events = []
    for token in doc:
        if token.pos_ == "VERB":
            events.append((token.text, token.lemma_))

    # -------- Event-Time Linking (Simple Rule Based) --------
    event_time_pairs = []
    for event in events:
        for time in time_entities:
            event_time_pairs.append((event[0], time[0]))

    return time_entities, events, event_time_pairs

# Example Text
text = """
Apple acquired Beats in 2014.
The company launched a new product last year.
Sundar Pichai became CEO of Google in 2015.
The meeting will happen tomorrow at 10 AM.
"""

time_entities, events, event_time_pairs = temporal_extraction(text)

print("---- Time Expressions ----")
for t in time_entities:
    print(t)

print("\n---- Events ----")
for e in events:
    print(e)

print("\n---- Event-Time Relationships ----")
for pair in event_time_pairs:
    print(pair)

"""Encoder-Decoder"""

# Install once
# !pip install transformers sentencepiece

from transformers import MarianMTModel, MarianTokenizer

# Load English → Hindi model
model_name = "Helsinki-NLP/opus-mt-en-hi"

tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

# -----------------------------
# User Input
# -----------------------------
text = input("Enter English sentence: ")

# Tokenize
inputs = tokenizer(text, return_tensors="pt", padding=True)

# Generate Translation
translated = model.generate(**inputs)

# Decode
output = tokenizer.decode(translated[0], skip_special_tokens=True)

print("\nEnglish:", text)
print("Hindi:", output)

"""BERT-Sentiment analysis"""

from transformers import pipeline

# Load pre-trained sentiment model (fine-tuned on 67,000+ movie reviews)
classifier = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

# Test sentences
texts = [
    "This is very bad",
    "I'm quite disappointed with the service.",
    "It was okay, nothing special.",
    "I absolutely loved the movie! The plot was brilliant.",
    "The food was cold and the service was terrible."
]

print("--- BERT Sentiment Analysis ---")
for text in texts:
    result = classifier(text)[0]
    print(f"Text  : {text}")
    print(f"Label : {result['label']}  |  Confidence: {result['score']:.4f}")
    print("-" * 55)

"""BERT- Summarization"""

!pip install transformers torch sentencepiece
from transformers import EncoderDecoderModel, BertTokenizer
import torch

# Load pretrained Bert2Bert summarization model
model_name = "patrickvonplaten/bert2bert_cnn_daily_mail"

tokenizer = BertTokenizer.from_pretrained(model_name)
model = EncoderDecoderModel.from_pretrained(model_name)

# Example long text (neutral)
text = """
Artificial Intelligence is transforming many industries by enabling machines to learn from data
and make intelligent decisions. It is widely used in healthcare, finance, transportation, and
education. Machine learning and deep learning are key subfields of AI that allow systems to
recognize patterns, automate tasks, and improve over time without explicit programming.
As technology advances, AI continues to shape the future of innovation and productivity.
"""

# Tokenize input
inputs = tokenizer(text, return_tensors="pt", max_length=512, truncation=True)

# Generate summary
summary_ids = model.generate(
    inputs["input_ids"],
    num_beams=4,
    max_length=80,
    min_length=25,
    length_penalty=2.0,
    early_stopping=True
)

# Decode summary
summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print("Original Text:\n", text)
print("\nSummary:\n", summary)

"""BERT- NER (Name Entity Recognition)"""

!pip install transformers torch
from transformers import pipeline

# Load pretrained BERT model for NER
ner_pipeline = pipeline(
    "ner",
    model="dslim/bert-base-NER",
    aggregation_strategy="simple"
)

# Sample text
text = "Apple Inc. was founded by Steve Jobs in California. Microsoft is headquartered in Redmond."

# Perform NER
entities = ner_pipeline(text)

# Print results
for entity in entities:
    print(f"Entity: {entity['word']}")
    print(f"Type: {entity['entity_group']}")
    print(f"Score: {round(entity['score'], 3)}")
    print("-" * 40)

"""BERT NSP (Next Sentence  prediction)"""

import torch
from transformers import BertTokenizer, BertForNextSentencePrediction

# ------------------ LOAD MODEL ------------------
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForNextSentencePrediction.from_pretrained('bert-base-uncased')

# ------------------ INPUT ------------------
sentence_A = input("Enter Sentence A: ")
sentence_B = input("Enter Sentence B: ")

# ------------------ TOKENIZATION ------------------
inputs = tokenizer(sentence_A, sentence_B, return_tensors='pt')

# ------------------ PREDICTION ------------------
outputs = model(**inputs)
logits = outputs.logits

# Convert to probabilities
probs = torch.softmax(logits, dim=1)

# ------------------ OUTPUT ------------------
is_next_prob = probs[0][0].item()     # Correct
not_next_prob = probs[0][1].item()   # Correct

print("\nIsNext Probability:", is_next_prob)
print("NotNext Probability:", not_next_prob)

# Final decision
prediction = torch.argmax(probs, dim=1).item()

if prediction == 0:
    print("Prediction: Sentence B follows Sentence A ✅")
else:
    print("Prediction: Sentence B does NOT follow Sentence A ❌")

